export enum ErrorCode {
    // Authentication & Authorization
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',

    // Validation
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',
    REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',

    // Business Logic
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
    BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    VALIDATION_FAILED = 'VALIDATION_FAILED',

    // Database
    DATABASE_ERROR = 'DATABASE_ERROR',
    DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
    FOREIGN_KEY_CONSTRAINT = 'FOREIGN_KEY_CONSTRAINT',

    // External Services
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    THIRD_PARTY_API_ERROR = 'THIRD_PARTY_API_ERROR',

    // System
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
